print("Hello, Git!")
print("Изучаю Git")
print("Проверяем staging area")
print("изменение сделано в Github")
print("Изменение из клонированного репозитория")
print("Изменение только в feature-test")
print("Новое изменение в feature-test")
